# Generated by Django 4.2.4 on 2023-09-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abecedario',
            fields=[
                ('idabc', models.AutoField(primary_key=True, serialize=False)),
                ('letra', models.CharField(max_length=1)),
                ('linkimg', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Explicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=500)),
                ('vid', models.CharField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owl_blue_app.categoria')),
            ],
        ),
    ]
