# Generated by Django 4.2.4 on 2023-09-22 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owl_blue_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.CharField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owl_blue_app.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Abecedario',
        ),
        migrations.DeleteModel(
            name='Explicaciones',
        ),
    ]
