# Generated by Django 4.2.4 on 2023-09-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owl_blue_app', '0003_abecedario_explicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('passwd', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='abecedario',
            name='letra',
            field=models.CharField(max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='abecedario',
            name='linkimg',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nom_categoria',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='explicaciones',
            name='img',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='explicaciones',
            name='vid',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
