# Generated by Django 4.2.4 on 2023-09-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owl_blue_app', '0004_usuarios_alter_abecedario_letra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abecedario',
            name='linkimg',
            field=models.CharField(max_length=700, unique=True),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='videos',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='explicaciones',
            name='img',
            field=models.CharField(max_length=700, unique=True),
        ),
        migrations.AlterField(
            model_name='explicaciones',
            name='vid',
            field=models.CharField(max_length=700, unique=True),
        ),
    ]
