# Generated by Django 4.2.4 on 2023-09-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owl_blue_app', '0005_alter_abecedario_linkimg_alter_actividades_videos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abecedario',
            name='linkimg',
            field=models.CharField(max_length=15000, unique=True),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='videos',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='explicaciones',
            name='img',
            field=models.CharField(max_length=15000, unique=True),
        ),
        migrations.AlterField(
            model_name='explicaciones',
            name='vid',
            field=models.CharField(max_length=15000, unique=True),
        ),
    ]
