# Generated by Django 4.2.4 on 2023-09-23 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owl_blue_app', '0008_alter_usuarios_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='passwd',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(16)]),
        ),
    ]
