# Generated by Django 4.2.4 on 2023-09-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owl_blue_app', '0011_alter_usuarios_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nom_categoria',
            new_name='categoria',
        ),
    ]
