# Generated by Django 4.2.4 on 2023-10-21 20:29

import django.core.validators
from django.db import migrations, models
import owl_blue_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('owl_blue_app', '0014_remove_usuarios_img_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]+$')])),
                ('passwd', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(16), owl_blue_app.models.validation_passwd])),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
