# Generated by Django 4.2.4 on 2023-10-21 21:50

import django.core.validators
from django.db import migrations, models
import owl_blue_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('owl_blue_app', '0016_alter_usuariosform_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosform',
            name='passwd',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(16), django.core.validators.RegexValidator(regex=owl_blue_app.models.validation_passwd)]),
        ),
    ]
