# Generated by Django 4.2.4 on 2023-10-21 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owl_blue_app', '0017_alter_usuariosform_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosform',
            name='passwd',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(16), django.core.validators.RegexValidator(regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,16}$')]),
        ),
    ]
