# Generated by Django 4.2.4 on 2023-10-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owl_blue_app', '0018_alter_usuariosform_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='alternativa1',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='actividades',
            name='alternativa2',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='actividades',
            name='alternativa3',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='actividades',
            name='pregunta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='actividades',
            name='respuesta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='videos',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
