# Generated by Django 4.2.4 on 2023-11-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owl_blue_app', '0019_actividades_alternativa1_actividades_alternativa2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='num_pregunta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='videos',
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
