# Generated by Django 4.2.4 on 2023-11-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owl_blue_app', '0020_actividades_num_pregunta_alter_actividades_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='videos',
            field=models.TextField(max_length=1000, unique=True),
        ),
    ]
