# Generated by Django 4.2.4 on 2023-11-12 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owl_blue_app', '0021_alter_actividades_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='img/defaultuser.png', null=True, upload_to='img/perfil/')),
                ('biografia', models.TextField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
