# Generated by Django 4.2.4 on 2023-11-12 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owl_blue_app', '0022_usuariomod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='passwd',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='username',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='biografia',
            field=models.TextField(default='¡Agrega tu biografía personalizada en el formulario!', max_length=1000),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='image',
            field=models.ImageField(blank=True, default='img/defaultuser.png', null=True, upload_to='img/perfil/'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UsuarioMod',
        ),
    ]
