# Generated by Django 4.2.4 on 2023-11-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owl_blue_app', '0024_infousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='infousuario',
            name='biografia',
            field=models.TextField(default='¡Agrega tu biografía personalizada en el formulario!', max_length=1000),
        ),
        migrations.AddField(
            model_name='infousuario',
            name='image',
            field=models.ImageField(blank=True, default='img/defaultuser.png', null=True, upload_to='img/perfil/'),
        ),
    ]
