# Generated by Django 4.2.4 on 2023-11-14 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owl_blue_app', '0026_alter_infousuario_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoLecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=False)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owl_blue_app.categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
