# Generated by Django 4.2.4 on 2023-11-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owl_blue_app', '0028_alter_explicaciones_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explicaciones',
            name='img',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
